### ISSUE TITLE
Questions regarding contribution to this repo

### ISSUE THREAD

**Issue by euler16** [chainer/models#26]
1. Is someone already working on the projects mentioned under 'in-progress' category. I know it sounds odd but I coded the Neural Representation of Sketch during an internship and thought of porting it to Chainer.

2. Can we add implementations from Visual Speech Recognition? or in general any other domain not listed ?

**Comment by aonotas** [comment]
Thank you! @euler16 🎉 
> `1. I coded the Neural Representation of Sketch during an internshi`

Very great work :)
Thank you for your contribution. 
Please send us PR. Maybe @koki0702 and @aonotas (me) can review it.

> `2. Can we add implementations from Visual Speech Recognition? or in general any other domain not listed ?`

Yes! Everyone can add implementations from any domains like visual speech recognition. 
I am so glad for your contribution.

If you have questions or comments, please tell us. 
We can help the Chainer community be more popular!

**Comment by euler16** [comment]
i actually coded VSR models in PyTorch. working on porting them. I am sorry had my mid-term exams

**Comment by aonotas** [comment]
Cool! 
Please send PR for us when you finished poting.

**Comment by euler16** [comment]
on it

**Comment by euler16** [comment]
I have written a port for Visual Speech Recognition part. it's available [here](https://github.com/euler16/Lipreading-Chainer). @Crissman I actually want to participate in GSoC under chainer's Expanding Knowledge Base proposal. would you guys consider this as part of my application?

**Comment by euler16** [comment]
I am currently coding SketchRNN for chainer.

**Comment by aonotas** [comment]
Maybe @Crissman are having vacation now.

**Comment by Crissman** [comment]
@euler16 Of course, we will consider contributions of examples for Chainer when evaluating GSoC candidates.

Thanks for your contribution!
